services:
  navidrome-artist-image-scraper:
    image: ghcr.io/xc518600/navidrome-artist-image-scraper:latest
    container_name: navidrome-artist-image-scraper
    restart: unless-stopped
    environment:
      TZ: Asia/Shanghai
      CONFIG_PATH: /config/config.json
      REPORT_PATH: /config/last-run-report.json
      WEB_HOST: 0.0.0.0
      WEB_PORT: 8080
      PROXY_HOST: http://192.168.3.30:20171
      HTTP_PROXY: http://192.168.3.30:20171
      HTTPS_PROXY: http://192.168.3.30:20171
    ports:
      - "38080:8080"
    volumes:
      - /vol1/1000/docker/navidrome-artist-image-scraper/config:/config
      - /vol1/1000/docker/Music/music_tag_web/config:/config/music_tag_web:ro
      - /vol1/1000/docker/navidrome-artist-image-scraper/cache:/app/cache
      - /vol4/1000/硬盘4国产电视剧/音乐:/music:rw
    working_dir: /app
